### ISSUE TITLE
Singleton not thread safe

### ISSUE THREAD

**Issue by abhishekhandacse** [Shellhead007/System-design#1]
https://github.com/Shellhead007/System-design/blob/master/SingletonConcept/Singleton.java

This implementation is not thread safe and might lead to race conditions in multithreaded environment.

**Comment by Shellhead007** [comment]
Yes, It is not thread safe. Just needed to add synchronized keyword in object making function as it may a case when two or more threads may try to create object and it will destroy the concept of singleton pattern.
Thanks for pointing it out.

**Comment by Shellhead007** [comment]
Added the small change. Although it is expensive and not optimized. Can be done in some other ways like locking.
